var BARS =
{
  'cols': ['A', 'B', 'C', 'D', 'E', 'F'],
  'rows':[
  { 'number' : 1,
    'cols': [
      { 'name': 'A1',
        'class': 'md-fab md-primary md-hue-2',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'B1',
        'class': 'md-fab md-primary',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'C1',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'D1',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'E1',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'F1',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
    ]
  },
  { 'number' : 2,
    'cols': [
      { 'name': 'A2',
        'class': 'md-fab md-primary md-hue-2',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'B2',
        'class': 'md-fab md-primary',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'C2',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'D2',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'E2',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'F2',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
    ]
  },
  { 'number' : 3,
    'cols': [
      { 'name': 'A3',
        'class': 'md-fab md-primary md-hue-2',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'B3',
        'class': 'md-fab md-primary',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'C3',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'D3',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'E3',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'F3',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
    ]
  },
  { 'number' : 4,
    'cols': [
      { 'name': 'A4',
        'class': 'md-fab md-primary md-hue-2',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'B4',
        'class': 'md-fab md-primary',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'C4',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'D4',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'E4',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'F4',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
    ]
  },
  { 'number' : 5,
    'cols': [
      { 'name': 'A5',
        'class': 'md-fab md-primary md-hue-2',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'B5',
        'class': 'md-fab md-primary',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'C5',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'D5',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'E5',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'F5',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
    ]
  },
  { 'number' : 6,
    'cols': [
      { 'name': 'A6',
        'class': 'md-fab md-primary md-hue-2',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'B6',
        'class': 'md-fab md-primary',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'C6',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'D6',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'E6',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
      { 'name': 'F6',
        'class': 'md-fab md-primary md-hue-1',
        'position': 0,
        'animation': { 'id': '', 'name': 'switch-off', 'color': 'rgba(255,255,255,0.5)', 'speed': 0, },
        'object': {},
        'active': false
      },
    ]
  },
],
'defaultColumnClasses': ['md-fab md-primary md-hue-2', 'md-fab md-primary', 'md-fab md-primary md-hue-1']
};

module.exports.bars = BARS;
